### ISSUE TITLE
Not an issue, rather a question!

### ISSUE THREAD

**Issue by ghost** [ceelery/Kast#1]
I'm not quite sure what the danger level of "P" is, if it's like a secret hardcore danger level meaning harder than S+ or what, I'd really like to know if this moon in particular is harder than titan which if so is amazing! the reason I decided to ask here is simply because I didn't have any other way of contacting you for the question, I don't expect this to be seen right away and all or maybe at all but I figured I'd at least ask :)

**Comment by ceelery** [comment]
Yes, that is the idea! Kast has more scrap, more enemies, and a larger facility than titan does.
