### ISSUE TITLE
Only host can enter interior dungeon

### ISSUE THREAD

**Issue by Blaz253** [ceelery/Kast#5]
like the name states, only the  host is able to enter the facility/dungeon in a multiplayer lobby, everyone else gets dropped into the void upon entering the doors falling for infinity,

**Comment by Blaz253** [comment]
I recant my bug report, turns out to be the dependency for this mod, Lethal Expansion, Keep up the planet making king!

**Comment by ceelery** [comment]
Yeahh LE is a little problematic, looking into the new alternative and will likely switch the moon's dependency.
